version: '3'
services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=laboR4toRio
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - /home/leandro/Code/nlp_to_sql/data:/usr/share/opensearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always

volumes:
  opensearch-data:

